from django.contrib import admin
from django.urls import path, include
from api.views import (
    AdminDashboardSummaryView,
    AdminDoctorCreateView,
    AdminDoctorRemoveView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserStatusUpdateView,
    AppointmentBookView,
    AppointmentListCreateView,
    AppointmentCancelView,
    AppointmentHideForPatientView,
    AppointmentListView,
    AppointmentMineView,
    AppointmentReportView,
    AppointmentRescheduleView,
    AppointmentUpdateView,
    CustomTokenObtainPairView,
    DoctorHistoryForAdminView,
    DoctorListView,
    DoctorProfileView,
    DoctorPublicSlotListView,
    DoctorSelfProfileView,
    DoctorSlotListCreateView,
    DoctorSlotUpdateView,
    DoctorWeeklyAvailabilityListCreateView,
    DoctorWeeklyAvailabilityUpdateView,
    PatientProfileView,
    PatientHistoryForDoctorAdminView,
    PatientMedicalProfileView,
    PatientMedicalProfileByIdView,
    RegisterView,
    SlotListByDoctorView,
    TodayAppointmentsView,
)
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/register/", RegisterView.as_view(), name="register"),
    path("api/auth/login/", CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/auth/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/doctors/", DoctorListView.as_view(), name="doctor_list"),
    path("api/doctors/profile/", DoctorProfileView.as_view(), name="doctors_profile"),
    path("api/doctors/<int:doctor_id>/slots/", DoctorPublicSlotListView.as_view(), name="doctor_public_slots"),
    path("api/slots/", SlotListByDoctorView.as_view(), name="slots_by_doctor"),
    path("api/doctor/profile/", DoctorSelfProfileView.as_view(), name="doctor_self_profile"),
    path("api/doctor/slots/", DoctorSlotListCreateView.as_view(), name="doctor_slot_list_create"),
    path("api/doctor/slots/<int:pk>/", DoctorSlotUpdateView.as_view(), name="doctor_slot_update"),
    path("api/doctor/weekly-availability/", DoctorWeeklyAvailabilityListCreateView.as_view(), name="doctor_weekly_availability_list_create"),
    path("api/doctor/weekly-availability/<int:pk>/", DoctorWeeklyAvailabilityUpdateView.as_view(), name="doctor_weekly_availability_update"),
    path("api/appointments/", AppointmentListCreateView.as_view(), name="appointment_list_create"),
    path("api/appointments/mine/", AppointmentMineView.as_view(), name="appointment_mine"),
    path("api/appointments/<int:appointment_id>/", AppointmentUpdateView.as_view(), name="appointment_update"),
    path("api/appointments/book/", AppointmentBookView.as_view(), name="appointment_book"),
    path("api/appointments/<int:appointment_id>/cancel/", AppointmentCancelView.as_view(), name="appointment_cancel"),
    path("api/appointments/<int:appointment_id>/hide/", AppointmentHideForPatientView.as_view(), name="appointment_hide_for_patient"),
    path("api/appointments/<int:appointment_id>/reschedule/", AppointmentRescheduleView.as_view(), name="appointment_reschedule"),
    path("api/appointments/<int:appointment_id>/report/", AppointmentReportView.as_view(), name="appointment_report"),
    path("api/appointments/today/", TodayAppointmentsView.as_view(), name="appointments_today"),
    path("api/patients/profile/", PatientProfileView.as_view(), name="patients_profile"),
    path("api/patient/medical-profile/", PatientMedicalProfileView.as_view(), name="patient_medical_profile"),
    path("api/patients/<int:patient_id>/medical-profile/", PatientMedicalProfileByIdView.as_view(), name="patient_medical_profile_by_id"),
    path("api/patients/<int:patient_id>/history/", PatientHistoryForDoctorAdminView.as_view(), name="patient_history"),
    path("api/admin/doctors/create/", AdminDoctorCreateView.as_view(), name="admin_doctor_create"),
    path("api/admin/doctors/<int:doctor_id>/remove/", AdminDoctorRemoveView.as_view(), name="admin_doctor_remove"),
    path("api/admin/doctors/<int:doctor_id>/history/", DoctorHistoryForAdminView.as_view(), name="admin_doctor_history"),
    path("api/admin/users/", AdminUserListView.as_view(), name="admin_user_list"),
    path("api/admin/users/<int:user_id>/profile/", AdminUserDetailView.as_view(), name="admin_user_detail"),
    path("api/admin/users/<int:user_id>/status/", AdminUserStatusUpdateView.as_view(), name="admin_user_status_update"),
    path("api/admin/dashboard-summary/", AdminDashboardSummaryView.as_view(), name="admin_dashboard_summary"),
    path("api-auth/", include("rest_framework.urls")),
]